CFLAGS=		-g -Wall -O2 #-Wextra
CPPFLAGS=	-DHAVE_KALLOC -DUSE_SIMDE -DSIMDE_ENABLE_NATIVE_ALIASES
INCLUDES=	-Isrc -Isrc/lib/simde
OBJS=		src/kthread.o src/kalloc.o src/misc.o src/bseq.o src/sketch.o src/sdust.o src/options.o src/index.o src/lchain.o src/align.o src/hit.o src/map.o src/format.o src/pe.o src/seed.o src/esterr.o src/splitidx.o \
			src/ksw2_extz2_simde.o src/ksw2_extd2_simde.o src/ksw2_exts2_simde.o src/ksw2_ll_simde.o
PROG=		minimap2
PROG_EXTRA=	sdust minimap2-lite
LIBS=		-lm -lz -lpthread

# Flags for ARM architecture with NEON
ifneq ($(arm_neon),) # if arm_neon is defined
ifeq ($(aarch64),)   # if aarch64 is not defined
	CFLAGS+=-D_FILE_OFFSET_BITS=64 -mfpu=neon -fsigned-char
else                 # if aarch64 is defined
	CFLAGS+=-D_FILE_OFFSET_BITS=64 -fsigned-char
endif
endif

# Address sanitizer flags
ifneq ($(asan),)
	CFLAGS+=-fsanitize=address
	LIBS+=-fsanitize=address
endif

# Thread sanitizer flags
ifneq ($(tsan),)
	CFLAGS+=-fsanitize=thread
	LIBS+=-fsanitize=thread
endif

.PHONY: all extra clean depend
.SUFFIXES: .c .cpp .o

# Compile .c files with gcc
.c.o:
		$(CC) -c $(CFLAGS) $(CPPFLAGS) $(INCLUDES) $< -o $@

# Compile .cpp files with g++
.cpp.o:
		$(CXX) -c $(CFLAGS) $(CPPFLAGS) $(INCLUDES) $< -o $@

all: $(PROG)

extra: all $(PROG_EXTRA)

minimap2: src/main.o libminimap2.a
		$(CXX) $(CFLAGS) src/main.o -o $@ -L. -lminimap2 $(LIBS)

minimap2-lite: src/example.o libminimap2.a
		$(CXX) $(CFLAGS) $< -o $@ -L. -lminimap2 $(LIBS)

libminimap2.a: $(OBJS)
		$(AR) -csru $@ $(OBJS)

sdust: src/sdust.c src/kalloc.o src/kalloc.h src/kdq.h src/kvec.h src/kseq.h src/ketopt.h src/sdust.h
		$(CC) -D_SDUST_MAIN $(CFLAGS) src/sdust.c src/kalloc.o -o $@ -lz

# SSE-specific targets
src/ksw2_ll_simde.o: src/ksw2_ll_sse.c src/ksw2.h src/kalloc.h
		$(CC) -c $(CFLAGS) -msse2 $(CPPFLAGS) $(INCLUDES) $< -o $@

src/ksw2_extz2_simde.o: src/ksw2_extz2_sse.c src/ksw2.h src/kalloc.h
		$(CC) -c $(CFLAGS) -msse4.1 $(CPPFLAGS) $(INCLUDES) $< -o $@

src/ksw2_extd2_simde.o: src/ksw2_extd2_sse.c src/ksw2.h src/kalloc.h
		$(CC) -c $(CFLAGS) -msse4.1 $(CPPFLAGS) $(INCLUDES) $< -o $@

src/ksw2_exts2_simde.o: src/ksw2_exts2_sse.c src/ksw2.h src/kalloc.h
		$(CC) -c $(CFLAGS) -msse4.1 $(CPPFLAGS) $(INCLUDES) $< -o $@

# other non-file targets
clean:
		rm -fr gmon.out src/*.o a.out $(PROG) $(PROG_EXTRA) *~ *.a *.dSYM build dist mappy*.so mappy.c python/mappy.c mappy.egg*

depend:
		(LC_ALL=C; export LC_ALL; makedepend -Y -- $(CFLAGS) $(CPPFLAGS) -- src/*.c src/*.cpp)

# DO NOT DELETE

src/align.o: src/minimap.h src/mmpriv.h src/bseq.h src/kseq.h src/ksw2.h src/kalloc.h
src/bseq.o: src/bseq.h src/kvec.h src/kalloc.h src/kseq.h
src/chain.o: src/minimap.h src/mmpriv.h src/bseq.h src/kseq.h src/kalloc.h
src/esterr.o: src/mmpriv.h src/minimap.h src/bseq.h src/kseq.h
src/example.o: src/minimap.h src/kseq.h
src/format.o: src/kalloc.h src/mmpriv.h src/minimap.h src/bseq.h src/kseq.h
src/hit.o: src/mmpriv.h src/minimap.h src/bseq.h src/kseq.h src/kalloc.h src/khash.h
src/index.o: src/kthread.h src/bseq.h src/minimap.h src/mmpriv.h src/kseq.h src/kvec.h src/kalloc.h src/khash.h
src/index.o: src/ksort.h
src/kalloc.o: src/kalloc.h
src/ksw2_extd2_sse.o: src/ksw2.h src/kalloc.h
src/ksw2_exts2_sse.o: src/ksw2.h src/kalloc.h
src/ksw2_extz2_sse.o: src/ksw2.h src/kalloc.h
src/ksw2_ll_sse.o: src/ksw2.h src/kalloc.h
src/kthread.o: src/kthread.h
src/main.o: src/bseq.h src/minimap.h src/mmpriv.h src/kseq.h src/ketopt.h
src/map.o: src/kthread.h src/kvec.h src/kalloc.h src/sdust.h src/mmpriv.h src/minimap.h src/bseq.h src/kseq.h
src/map.o: src/khash.h src/ksort.h
src/misc.o: src/mmpriv.h src/minimap.h src/bseq.h src/kseq.h src/ksort.h
src/options.o: src/mmpriv.h src/minimap.h src/bseq.h src/kseq.h
src/pe.o: src/mmpriv.h src/minimap.h src/bseq.h src/kseq.h src/kvec.h src/kalloc.h src/ksort.h
src/sdust.o: src/kalloc.h src/kdq.h src/kvec.h src/sdust.h
src/self-chain.o: src/minimap.h src/kseq.h
src/sketch.o: src/kvec.h src/kalloc.h src/mmpriv.h src/minimap.h src/bseq.h src/kseq.h
src/splitidx.o: src/mmpriv.h src/minimap.h src/bseq.h src/kseq.h
